"""initial

Revision ID: 0abdd78b9b2c
Create Date: 2022-09-16 18:42:56.454611

"""
from alembic import op # noqa
import sqlalchemy as sa # noqa
import sqlmodel # noqa


# revision identifiers, used by Alembic.
revision = '0abdd78b9b2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
